// Bron: CBS Gemeentelijke indeling 2024 (https://www.cbs.nl/nl-nl/onze-diensten/methoden/classificaties/overig/gemeentelijke-indelingen-per-jaar)
// Gebruikte codes zijn CBS-gemeentecodes (met 'gm'-prefix) en provinciecodes.

export const NL_PROVINCES = [
  { code: "20", name: "Groningen" },
  { code: "21", name: "Friesland" },
  { code: "22", name: "Drenthe" },
  { code: "23", name: "Overijssel" },
  { code: "24", name: "Flevoland" },
  { code: "25", name: "Gelderland" },
  { code: "26", name: "Utrecht" },
  { code: "27", name: "Noord-Holland" },
  { code: "28", name: "Zuid-Holland" },
  { code: "29", name: "Zeeland" },
  { code: "30", name: "Noord-Brabant" },
  { code: "31", name: "Limburg" },
] as const;

export const NL_INDUSTRY_NETWORKS = [
  "Bouw",
  "Horeca & food",
  "Productie",
  "Retail",
  "Technologie",
  "Transport & logistiek",
  "Verpakkingen",
  "Zorg",
  "Import & export",
  "Financieel",
  "Agrarisch",
  "Vastgoed",
  "Zakelijke dienstverlening",
  "Groothandel",
  "Energie & duurzaamheid",
] as const;

export type DutchProvince = (typeof NL_PROVINCES)[number]["name"];

export const NL_MUNICIPALITIES: { id: string; name: string; province: DutchProvince }[] = [
  { id: "gm1979", name: "Eemsdelta", province: "Groningen" },
  { id: "gm0014", name: "Groningen", province: "Groningen" },
  { id: "gm1966", name: "Het Hogeland", province: "Groningen" },
  { id: "gm1952", name: "Midden-Groningen", province: "Groningen" },
  { id: "gm1895", name: "Oldambt", province: "Groningen" },
  { id: "gm0765", name: "Pekela", province: "Groningen" },
  { id: "gm0037", name: "Stadskanaal", province: "Groningen" },
  { id: "gm0047", name: "Veendam", province: "Groningen" },
  { id: "gm1969", name: "Westerkwartier", province: "Groningen" },
  { id: "gm1950", name: "Westerwolde", province: "Groningen" },
  { id: "gm0059", name: "Achtkarspelen", province: "Friesland" },
  { id: "gm0060", name: "Ameland", province: "Friesland" },
  { id: "gm1891", name: "Dantumadiel", province: "Friesland" },
  { id: "gm1940", name: "De Fryske Marren", province: "Friesland" },
  { id: "gm0072", name: "Harlingen", province: "Friesland" },
  { id: "gm0074", name: "Heerenveen", province: "Friesland" },
  { id: "gm0080", name: "Leeuwarden", province: "Friesland" },
  { id: "gm1970", name: "Noardeast-Fryslân", province: "Friesland" },
  { id: "gm0085", name: "Ooststellingwerf", province: "Friesland" },
  { id: "gm0086", name: "Opsterland", province: "Friesland" },
  { id: "gm0088", name: "Schiermonnikoog", province: "Friesland" },
  { id: "gm0090", name: "Smallingerland", province: "Friesland" },
  { id: "gm1900", name: "Súdwest-Fryslân", province: "Friesland" },
  { id: "gm0093", name: "Terschelling", province: "Friesland" },
  { id: "gm0737", name: "Tytsjerksteradiel", province: "Friesland" },
  { id: "gm0096", name: "Vlieland", province: "Friesland" },
  { id: "gm1949", name: "Waadhoeke", province: "Friesland" },
  { id: "gm0098", name: "Weststellingwerf", province: "Friesland" },
  { id: "gm1680", name: "Aa en Hunze", province: "Drenthe" },
  { id: "gm0106", name: "Assen", province: "Drenthe" },
  { id: "gm1681", name: "Borger-Odoorn", province: "Drenthe" },
  { id: "gm0109", name: "Coevorden", province: "Drenthe" },
  { id: "gm1690", name: "De Wolden", province: "Drenthe" },
  { id: "gm0114", name: "Emmen", province: "Drenthe" },
  { id: "gm0118", name: "Hoogeveen", province: "Drenthe" },
  { id: "gm0119", name: "Meppel", province: "Drenthe" },
  { id: "gm1731", name: "Midden-Drenthe", province: "Drenthe" },
  { id: "gm1699", name: "Noordenveld", province: "Drenthe" },
  { id: "gm1730", name: "Tynaarlo", province: "Drenthe" },
  { id: "gm1701", name: "Westerveld", province: "Drenthe" },
  { id: "gm0141", name: "Almelo", province: "Overijssel" },
  { id: "gm0147", name: "Borne", province: "Overijssel" },
  { id: "gm0148", name: "Dalfsen", province: "Overijssel" },
  { id: "gm0150", name: "Deventer", province: "Overijssel" },
  { id: "gm1774", name: "Dinkelland", province: "Overijssel" },
  { id: "gm0153", name: "Enschede", province: "Overijssel" },
  { id: "gm0158", name: "Haaksbergen", province: "Overijssel" },
  { id: "gm0160", name: "Hardenberg", province: "Overijssel" },
  { id: "gm0163", name: "Hellendoorn", province: "Overijssel" },
  { id: "gm0164", name: "Hengelo", province: "Overijssel" },
  { id: "gm1735", name: "Hof van Twente", province: "Overijssel" },
  { id: "gm0166", name: "Kampen", province: "Overijssel" },
  { id: "gm0168", name: "Losser", province: "Overijssel" },
  { id: "gm0173", name: "Oldenzaal", province: "Overijssel" },
  { id: "gm1773", name: "Olst-Wijhe", province: "Overijssel" },
  { id: "gm0175", name: "Ommen", province: "Overijssel" },
  { id: "gm0177", name: "Raalte", province: "Overijssel" },
  { id: "gm1742", name: "Rijssen-Holten", province: "Overijssel" },
  { id: "gm0180", name: "Staphorst", province: "Overijssel" },
  { id: "gm1708", name: "Steenwijkerland", province: "Overijssel" },
  { id: "gm0183", name: "Tubbergen", province: "Overijssel" },
  { id: "gm1700", name: "Twenterand", province: "Overijssel" },
  { id: "gm0189", name: "Wierden", province: "Overijssel" },
  { id: "gm1896", name: "Zwartewaterland", province: "Overijssel" },
  { id: "gm0193", name: "Zwolle", province: "Overijssel" },
  { id: "gm0034", name: "Almere", province: "Flevoland" },
  { id: "gm0303", name: "Dronten", province: "Flevoland" },
  { id: "gm0995", name: "Lelystad", province: "Flevoland" },
  { id: "gm0171", name: "Noordoostpolder", province: "Flevoland" },
  { id: "gm0184", name: "Urk", province: "Flevoland" },
  { id: "gm0050", name: "Zeewolde", province: "Flevoland" },
  { id: "gm0197", name: "Aalten", province: "Gelderland" },
  { id: "gm0200", name: "Apeldoorn", province: "Gelderland" },
  { id: "gm0202", name: "Arnhem", province: "Gelderland" },
  { id: "gm0203", name: "Barneveld", province: "Gelderland" },
  { id: "gm1945", name: "Berg en Dal", province: "Gelderland" },
  { id: "gm1859", name: "Berkelland", province: "Gelderland" },
  { id: "gm0209", name: "Beuningen", province: "Gelderland" },
  { id: "gm1876", name: "Bronckhorst", province: "Gelderland" },
  { id: "gm0213", name: "Brummen", province: "Gelderland" },
  { id: "gm0214", name: "Buren", province: "Gelderland" },
  { id: "gm0216", name: "Culemborg", province: "Gelderland" },
  { id: "gm0221", name: "Doesburg", province: "Gelderland" },
  { id: "gm0222", name: "Doetinchem", province: "Gelderland" },
  { id: "gm0225", name: "Druten", province: "Gelderland" },
  { id: "gm0226", name: "Duiven", province: "Gelderland" },
  { id: "gm0228", name: "Ede", province: "Gelderland" },
  { id: "gm0230", name: "Elburg", province: "Gelderland" },
  { id: "gm0232", name: "Epe", province: "Gelderland" },
  { id: "gm0233", name: "Ermelo", province: "Gelderland" },
  { id: "gm0243", name: "Harderwijk", province: "Gelderland" },
  { id: "gm0244", name: "Hattem", province: "Gelderland" },
  { id: "gm0246", name: "Heerde", province: "Gelderland" },
  { id: "gm0252", name: "Heumen", province: "Gelderland" },
  { id: "gm1705", name: "Lingewaard", province: "Gelderland" },
  { id: "gm0262", name: "Lochem", province: "Gelderland" },
  { id: "gm0263", name: "Maasdriel", province: "Gelderland" },
  { id: "gm1955", name: "Montferland", province: "Gelderland" },
  { id: "gm1740", name: "Neder-Betuwe", province: "Gelderland" },
  { id: "gm0267", name: "Nijkerk", province: "Gelderland" },
  { id: "gm0268", name: "Nijmegen", province: "Gelderland" },
  { id: "gm0302", name: "Nunspeet", province: "Gelderland" },
  { id: "gm0269", name: "Oldebroek", province: "Gelderland" },
  { id: "gm1586", name: "Oost Gelre", province: "Gelderland" },
  { id: "gm1509", name: "Oude IJsselstreek", province: "Gelderland" },
  { id: "gm1734", name: "Overbetuwe", province: "Gelderland" },
  { id: "gm0273", name: "Putten", province: "Gelderland" },
  { id: "gm0274", name: "Renkum", province: "Gelderland" },
  { id: "gm0275", name: "Rheden", province: "Gelderland" },
  { id: "gm0277", name: "Rozendaal", province: "Gelderland" },
  { id: "gm0279", name: "Scherpenzeel", province: "Gelderland" },
  { id: "gm0281", name: "Tiel", province: "Gelderland" },
  { id: "gm0285", name: "Voorst", province: "Gelderland" },
  { id: "gm0289", name: "Wageningen", province: "Gelderland" },
  { id: "gm1960", name: "West Betuwe", province: "Gelderland" },
  { id: "gm0668", name: "West Maas en Waal", province: "Gelderland" },
  { id: "gm0293", name: "Westervoort", province: "Gelderland" },
  { id: "gm0296", name: "Wijchen", province: "Gelderland" },
  { id: "gm0294", name: "Winterswijk", province: "Gelderland" },
  { id: "gm0297", name: "Zaltbommel", province: "Gelderland" },
  { id: "gm0299", name: "Zevenaar", province: "Gelderland" },
  { id: "gm0301", name: "Zutphen", province: "Gelderland" },
  { id: "gm0307", name: "Amersfoort", province: "Utrecht" },
  { id: "gm0308", name: "Baarn", province: "Utrecht" },
  { id: "gm0312", name: "Bunnik", province: "Utrecht" },
  { id: "gm0313", name: "Bunschoten", province: "Utrecht" },
  { id: "gm0310", name: "De Bilt", province: "Utrecht" },
  { id: "gm0736", name: "De Ronde Venen", province: "Utrecht" },
  { id: "gm0317", name: "Eemnes", province: "Utrecht" },
  { id: "gm0321", name: "Houten", province: "Utrecht" },
  { id: "gm0353", name: "IJsselstein", province: "Utrecht" },
  { id: "gm0327", name: "Leusden", province: "Utrecht" },
  { id: "gm0331", name: "Lopik", province: "Utrecht" },
  { id: "gm0335", name: "Montfoort", province: "Utrecht" },
  { id: "gm0356", name: "Nieuwegein", province: "Utrecht" },
  { id: "gm0589", name: "Oudewater", province: "Utrecht" },
  { id: "gm0339", name: "Renswoude", province: "Utrecht" },
  { id: "gm0340", name: "Rhenen", province: "Utrecht" },
  { id: "gm0342", name: "Soest", province: "Utrecht" },
  { id: "gm1904", name: "Stichtse Vecht", province: "Utrecht" },
  { id: "gm0344", name: "Utrecht", province: "Utrecht" },
  { id: "gm1581", name: "Utrechtse Heuvelrug", province: "Utrecht" },
  { id: "gm0345", name: "Veenendaal", province: "Utrecht" },
  { id: "gm1961", name: "Vijfheerenlanden", province: "Utrecht" },
  { id: "gm0352", name: "Wijk bij Duurstede", province: "Utrecht" },
  { id: "gm0632", name: "Woerden", province: "Utrecht" },
  { id: "gm0351", name: "Woudenberg", province: "Utrecht" },
  { id: "gm0355", name: "Zeist", province: "Utrecht" },
  { id: "gm0358", name: "Aalsmeer", province: "Noord-Holland" },
  { id: "gm0361", name: "Alkmaar", province: "Noord-Holland" },
  { id: "gm0362", name: "Amstelveen", province: "Noord-Holland" },
  { id: "gm0363", name: "Amsterdam", province: "Noord-Holland" },
  { id: "gm0373", name: "Bergen", province: "Noord-Holland" },
  { id: "gm0375", name: "Beverwijk", province: "Noord-Holland" },
  { id: "gm0376", name: "Blaricum", province: "Noord-Holland" },
  { id: "gm0377", name: "Bloemendaal", province: "Noord-Holland" },
  { id: "gm0383", name: "Castricum", province: "Noord-Holland" },
  { id: "gm0400", name: "Den Helder", province: "Noord-Holland" },
  { id: "gm0384", name: "Diemen", province: "Noord-Holland" },
  { id: "gm1980", name: "Dijk en Waard", province: "Noord-Holland" },
  { id: "gm0498", name: "Drechterland", province: "Noord-Holland" },
  { id: "gm0385", name: "Edam-Volendam", province: "Noord-Holland" },
  { id: "gm0388", name: "Enkhuizen", province: "Noord-Holland" },
  { id: "gm1942", name: "Gooise Meren", province: "Noord-Holland" },
  { id: "gm0392", name: "Haarlem", province: "Noord-Holland" },
  { id: "gm0394", name: "Haarlemmermeer", province: "Noord-Holland" },
  { id: "gm0396", name: "Heemskerk", province: "Noord-Holland" },
  { id: "gm0397", name: "Heemstede", province: "Noord-Holland" },
  { id: "gm0399", name: "Heiloo", province: "Noord-Holland" },
  { id: "gm0402", name: "Hilversum", province: "Noord-Holland" },
  { id: "gm1911", name: "Hollands Kroon", province: "Noord-Holland" },
  { id: "gm0405", name: "Hoorn", province: "Noord-Holland" },
  { id: "gm0406", name: "Huizen", province: "Noord-Holland" },
  { id: "gm1598", name: "Koggenland", province: "Noord-Holland" },
  { id: "gm0415", name: "Landsmeer", province: "Noord-Holland" },
  { id: "gm0417", name: "Laren", province: "Noord-Holland" },
  { id: "gm0420", name: "Medemblik", province: "Noord-Holland" },
  { id: "gm0431", name: "Oostzaan", province: "Noord-Holland" },
  { id: "gm0432", name: "Opmeer", province: "Noord-Holland" },
  { id: "gm0437", name: "Ouder-Amstel", province: "Noord-Holland" },
  { id: "gm0439", name: "Purmerend", province: "Noord-Holland" },
  { id: "gm0441", name: "Schagen", province: "Noord-Holland" },
  { id: "gm0532", name: "Stede Broec", province: "Noord-Holland" },
  { id: "gm0448", name: "Texel", province: "Noord-Holland" },
  { id: "gm0450", name: "Uitgeest", province: "Noord-Holland" },
  { id: "gm0451", name: "Uithoorn", province: "Noord-Holland" },
  { id: "gm0453", name: "Velsen", province: "Noord-Holland" },
  { id: "gm0852", name: "Waterland", province: "Noord-Holland" },
  { id: "gm1696", name: "Wijdemeren", province: "Noord-Holland" },
  { id: "gm0880", name: "Wormerland", province: "Noord-Holland" },
  { id: "gm0479", name: "Zaanstad", province: "Noord-Holland" },
  { id: "gm0473", name: "Zandvoort", province: "Noord-Holland" },
  { id: "gm0518", name: "'s-Gravenhage", province: "Zuid-Holland" },
  { id: "gm0482", name: "Alblasserdam", province: "Zuid-Holland" },
  { id: "gm0613", name: "Albrandswaard", province: "Zuid-Holland" },
  { id: "gm0484", name: "Alphen aan den Rijn", province: "Zuid-Holland" },
  { id: "gm0489", name: "Barendrecht", province: "Zuid-Holland" },
  { id: "gm1901", name: "Bodegraven-Reeuwijk", province: "Zuid-Holland" },
  { id: "gm0502", name: "Capelle aan den IJssel", province: "Zuid-Holland" },
  { id: "gm0503", name: "Delft", province: "Zuid-Holland" },
  { id: "gm0505", name: "Dordrecht", province: "Zuid-Holland" },
  { id: "gm1924", name: "Goeree-Overflakkee", province: "Zuid-Holland" },
  { id: "gm0512", name: "Gorinchem", province: "Zuid-Holland" },
  { id: "gm0513", name: "Gouda", province: "Zuid-Holland" },
  { id: "gm0523", name: "Hardinxveld-Giessendam", province: "Zuid-Holland" },
  { id: "gm0531", name: "Hendrik-Ido-Ambacht", province: "Zuid-Holland" },
  { id: "gm0534", name: "Hillegom", province: "Zuid-Holland" },
  { id: "gm1963", name: "Hoeksche Waard", province: "Zuid-Holland" },
  { id: "gm1884", name: "Kaag en Braassem", province: "Zuid-Holland" },
  { id: "gm0537", name: "Katwijk", province: "Zuid-Holland" },
  { id: "gm0542", name: "Krimpen aan den IJssel", province: "Zuid-Holland" },
  { id: "gm1931", name: "Krimpenerwaard", province: "Zuid-Holland" },
  { id: "gm1621", name: "Lansingerland", province: "Zuid-Holland" },
  { id: "gm0546", name: "Leiden", province: "Zuid-Holland" },
  { id: "gm0547", name: "Leiderdorp", province: "Zuid-Holland" },
  { id: "gm1916", name: "Leidschendam-Voorburg", province: "Zuid-Holland" },
  { id: "gm0553", name: "Lisse", province: "Zuid-Holland" },
  { id: "gm0556", name: "Maassluis", province: "Zuid-Holland" },
  { id: "gm1842", name: "Midden-Delfland", province: "Zuid-Holland" },
  { id: "gm1978", name: "Molenlanden", province: "Zuid-Holland" },
  { id: "gm0569", name: "Nieuwkoop", province: "Zuid-Holland" },
  { id: "gm1930", name: "Nissewaard", province: "Zuid-Holland" },
  { id: "gm0575", name: "Noordwijk", province: "Zuid-Holland" },
  { id: "gm0579", name: "Oegstgeest", province: "Zuid-Holland" },
  { id: "gm0590", name: "Papendrecht", province: "Zuid-Holland" },
  { id: "gm1926", name: "Pijnacker-Nootdorp", province: "Zuid-Holland" },
  { id: "gm0597", name: "Ridderkerk", province: "Zuid-Holland" },
  { id: "gm0603", name: "Rijswijk", province: "Zuid-Holland" },
  { id: "gm0599", name: "Rotterdam", province: "Zuid-Holland" },
  { id: "gm0606", name: "Schiedam", province: "Zuid-Holland" },
  { id: "gm0610", name: "Sliedrecht", province: "Zuid-Holland" },
  { id: "gm1525", name: "Teylingen", province: "Zuid-Holland" },
  { id: "gm0622", name: "Vlaardingen", province: "Zuid-Holland" },
  { id: "gm1992", name: "Voorne aan Zee", province: "Zuid-Holland" },
  { id: "gm0626", name: "Voorschoten", province: "Zuid-Holland" },
  { id: "gm0627", name: "Waddinxveen", province: "Zuid-Holland" },
  { id: "gm0629", name: "Wassenaar", province: "Zuid-Holland" },
  { id: "gm1783", name: "Westland", province: "Zuid-Holland" },
  { id: "gm0637", name: "Zoetermeer", province: "Zuid-Holland" },
  { id: "gm0638", name: "Zoeterwoude", province: "Zuid-Holland" },
  { id: "gm1892", name: "Zuidplas", province: "Zuid-Holland" },
  { id: "gm0642", name: "Zwijndrecht", province: "Zuid-Holland" },
  { id: "gm0654", name: "Borsele", province: "Zeeland" },
  { id: "gm0664", name: "Goes", province: "Zeeland" },
  { id: "gm0677", name: "Hulst", province: "Zeeland" },
  { id: "gm0678", name: "Kapelle", province: "Zeeland" },
  { id: "gm0687", name: "Middelburg", province: "Zeeland" },
  { id: "gm1695", name: "Noord-Beveland", province: "Zeeland" },
  { id: "gm0703", name: "Reimerswaal", province: "Zeeland" },
  { id: "gm1676", name: "Schouwen-Duiveland", province: "Zeeland" },
  { id: "gm1714", name: "Sluis", province: "Zeeland" },
  { id: "gm0715", name: "Terneuzen", province: "Zeeland" },
  { id: "gm0716", name: "Tholen", province: "Zeeland" },
  { id: "gm0717", name: "Veere", province: "Zeeland" },
  { id: "gm0718", name: "Vlissingen", province: "Zeeland" },
  { id: "gm0796", name: "'s-Hertogenbosch", province: "Noord-Brabant" },
  { id: "gm1723", name: "Alphen-Chaam", province: "Noord-Brabant" },
  { id: "gm1959", name: "Altena", province: "Noord-Brabant" },
  { id: "gm0743", name: "Asten", province: "Noord-Brabant" },
  { id: "gm0744", name: "Baarle-Nassau", province: "Noord-Brabant" },
  { id: "gm1724", name: "Bergeijk", province: "Noord-Brabant" },
  { id: "gm0748", name: "Bergen op Zoom", province: "Noord-Brabant" },
  { id: "gm1721", name: "Bernheze", province: "Noord-Brabant" },
  { id: "gm0753", name: "Best", province: "Noord-Brabant" },
  { id: "gm1728", name: "Bladel", province: "Noord-Brabant" },
  { id: "gm0755", name: "Boekel", province: "Noord-Brabant" },
  { id: "gm0757", name: "Boxtel", province: "Noord-Brabant" },
  { id: "gm0758", name: "Breda", province: "Noord-Brabant" },
  { id: "gm1706", name: "Cranendonck", province: "Noord-Brabant" },
  { id: "gm0762", name: "Deurne", province: "Noord-Brabant" },
  { id: "gm0766", name: "Dongen", province: "Noord-Brabant" },
  { id: "gm1719", name: "Drimmelen", province: "Noord-Brabant" },
  { id: "gm0770", name: "Eersel", province: "Noord-Brabant" },
  { id: "gm0772", name: "Eindhoven", province: "Noord-Brabant" },
  { id: "gm0777", name: "Etten-Leur", province: "Noord-Brabant" },
  { id: "gm0779", name: "Geertruidenberg", province: "Noord-Brabant" },
  { id: "gm1771", name: "Geldrop-Mierlo", province: "Noord-Brabant" },
  { id: "gm1652", name: "Gemert-Bakel", province: "Noord-Brabant" },
  { id: "gm0784", name: "Gilze en Rijen", province: "Noord-Brabant" },
  { id: "gm0785", name: "Goirle", province: "Noord-Brabant" },
  { id: "gm1655", name: "Halderberge", province: "Noord-Brabant" },
  { id: "gm1658", name: "Heeze-Leende", province: "Noord-Brabant" },
  { id: "gm0794", name: "Helmond", province: "Noord-Brabant" },
  { id: "gm0797", name: "Heusden", province: "Noord-Brabant" },
  { id: "gm0798", name: "Hilvarenbeek", province: "Noord-Brabant" },
  { id: "gm1659", name: "Laarbeek", province: "Noord-Brabant" },
  { id: "gm1982", name: "Land van Cuijk", province: "Noord-Brabant" },
  { id: "gm0809", name: "Loon op Zand", province: "Noord-Brabant" },
  { id: "gm1991", name: "Maashorst", province: "Noord-Brabant" },
  { id: "gm1948", name: "Meierijstad", province: "Noord-Brabant" },
  { id: "gm1709", name: "Moerdijk", province: "Noord-Brabant" },
  { id: "gm0820", name: "Nuenen, Gerwen en Nederwetten", province: "Noord-Brabant" },
  { id: "gm0823", name: "Oirschot", province: "Noord-Brabant" },
  { id: "gm0824", name: "Oisterwijk", province: "Noord-Brabant" },
  { id: "gm0826", name: "Oosterhout", province: "Noord-Brabant" },
  { id: "gm0828", name: "Oss", province: "Noord-Brabant" },
  { id: "gm1667", name: "Reusel-De Mierden", province: "Noord-Brabant" },
  { id: "gm1674", name: "Roosendaal", province: "Noord-Brabant" },
  { id: "gm0840", name: "Rucphen", province: "Noord-Brabant" },
  { id: "gm0845", name: "Sint-Michielsgestel", province: "Noord-Brabant" },
  { id: "gm0847", name: "Someren", province: "Noord-Brabant" },
  { id: "gm0848", name: "Son en Breugel", province: "Noord-Brabant" },
  { id: "gm0851", name: "Steenbergen", province: "Noord-Brabant" },
  { id: "gm0855", name: "Tilburg", province: "Noord-Brabant" },
  { id: "gm0858", name: "Valkenswaard", province: "Noord-Brabant" },
  { id: "gm0861", name: "Veldhoven", province: "Noord-Brabant" },
  { id: "gm0865", name: "Vught", province: "Noord-Brabant" },
  { id: "gm0866", name: "Waalre", province: "Noord-Brabant" },
  { id: "gm0867", name: "Waalwijk", province: "Noord-Brabant" },
  { id: "gm0873", name: "Woensdrecht", province: "Noord-Brabant" },
  { id: "gm0879", name: "Zundert", province: "Noord-Brabant" },
  { id: "gm0888", name: "Beek", province: "Limburg" },
  { id: "gm1954", name: "Beekdaelen", province: "Limburg" },
  { id: "gm0889", name: "Beesel", province: "Limburg" },
  { id: "gm0893", name: "Bergen", province: "Limburg" },
  { id: "gm0899", name: "Brunssum", province: "Limburg" },
  { id: "gm1711", name: "Echt-Susteren", province: "Limburg" },
  { id: "gm1903", name: "Eijsden-Margraten", province: "Limburg" },
  { id: "gm0907", name: "Gennep", province: "Limburg" },
  { id: "gm1729", name: "Gulpen-Wittem", province: "Limburg" },
  { id: "gm0917", name: "Heerlen", province: "Limburg" },
  { id: "gm1507", name: "Horst aan de Maas", province: "Limburg" },
  { id: "gm0928", name: "Kerkrade", province: "Limburg" },
  { id: "gm0882", name: "Landgraaf", province: "Limburg" },
  { id: "gm1640", name: "Leudal", province: "Limburg" },
  { id: "gm1641", name: "Maasgouw", province: "Limburg" },
  { id: "gm0935", name: "Maastricht", province: "Limburg" },
  { id: "gm0938", name: "Meerssen", province: "Limburg" },
  { id: "gm0944", name: "Mook en Middelaar", province: "Limburg" },
  { id: "gm0946", name: "Nederweert", province: "Limburg" },
  { id: "gm1894", name: "Peel en Maas", province: "Limburg" },
  { id: "gm1669", name: "Roerdalen", province: "Limburg" },
  { id: "gm0957", name: "Roermond", province: "Limburg" },
  { id: "gm0965", name: "Simpelveld", province: "Limburg" },
  { id: "gm1883", name: "Sittard-Geleen", province: "Limburg" },
  { id: "gm0971", name: "Stein", province: "Limburg" },
  { id: "gm0981", name: "Vaals", province: "Limburg" },
  { id: "gm0994", name: "Valkenburg aan de Geul", province: "Limburg" },
  { id: "gm0983", name: "Venlo", province: "Limburg" },
  { id: "gm0984", name: "Venray", province: "Limburg" },
  { id: "gm0986", name: "Voerendaal", province: "Limburg" },
  { id: "gm0988", name: "Weert", province: "Limburg" },
];

export const MUNICIPALITY_BY_NAME = new Map(
  NL_MUNICIPALITIES.map((m) => [m.name, m])
);

export const MUNICIPALITY_BY_ID = new Map(
  NL_MUNICIPALITIES.map((m) => [m.id, m])
);

export function getProvinceByName(name: string) {
  return NL_PROVINCES.find((p) => p.name === name);
}

export function getMunicipalityByName(name: string) {
  return MUNICIPALITY_BY_NAME.get(name);
}

export function getMunicipalitiesByProvince(provinceName: string) {
  return NL_MUNICIPALITIES.filter((m) => m.province === provinceName);
}
